config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'

  resources :users, only: %i[new create show edit update]
  resources :schedules, only: %i[index new create show edit update destroy] do
    resources :tasks, only: %i[create edit update destroy toggle_complete calculate_task_position], shallow: true do
      member do
        patch :toggle_complete
      end
    end
  end

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  post '/guest_login', to: 'sessions#guest_login'
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :name, presence: true, length: { maximum: 255 }
  validates :email, presence: true, uniqueness: true

  has_many :schedules, dependent: :destroy
  has_many :tasks, dependent: :destroy

  def own?(object)
    id == object&.user_id
  end

  def profile_icon
    case completed_tasks_count
    when 0..1
      'icon_stage_1.png'
    when 2..4
      'icon_stage_2.png'
    when 5..10
      'icon_stage_3.png'
    else
      'icon_stage_4.png'
    end
  end

  private

  def completed_tasks_count
    tasks.where(status: :completed).count
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id  # 新規登録後にログイン状態にする
      redirect_to root_path, success: t('.success')
    else
      flash.now[:danger] = t('.failure')
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user, success: t('.success')
    else
      flash.now[:danger] = t('.failure')
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container mt-5">
  <h1>プロフィール編集</h1>
  <div class="profile-icon mb-4">
    <h3>プロフィールアイコン</h3>
    <%= image_tag @user.profile_icon, alt: 'プロフィールアイコン', class: 'profile-icon-img' %>
  </div>
  <%= form_with(model: @user, local: true) do |form| %>
    <div class="form-group">
      <%= form.label :name, '名前' %>
      <%= form.text_field :name, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= form.label :email, 'メールアドレス' %>
      <%= form.email_field :email, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= form.label :password, 'パスワード' %>
      <%= form.password_field :password, class: 'form-control' %>
    </div>
    <%= form.submit '更新', class: 'btn btn-primary' %>
  <% end %>
  <%= link_to 'キャンセル', user_path(@user), class: 'btn btn-secondary mt-2' %>
</div>

app/views/users/new.html.erb
<div class="container mt-5">
  <div class="pizza-box">
    <h1 class="h3">新規登録</h1>
    <%= form_with model: @user, url: users_path, local: true, class: "needs-validation" do |f| %>
      <div class="mb-3">
        <%= f.label :name, "名前", class: "form-label" %>
        <%= f.text_field :name, class: "form-control", required: true %>
      </div>
      <div class="mb-3">
        <%= f.label :email, "メールアドレス", class: "form-label" %>
        <%= f.email_field :email, class: "form-control", required: true %>
      </div>
      <div class="mb-3">
        <%= f.label :password, "パスワード", class: "form-label" %>
        <%= f.password_field :password, class: "form-control", required: true %>
      </div>
      <div class="d-grid">
        <%= f.submit "登録する", class: "btn btn-primary btn-lg" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container mt-5">
  <h1>プロフィール</h1>
  <p>
    <strong>プロフィールアイコン:</strong><br>
    <%= image_tag asset_path(@user.profile_icon), alt: "プロフィールアイコン", class: "profile-icon" if @user.profile_icon.present? %>
  </p>
  <p>
    <strong>名前:</strong>
    <%= @user.name %>
  </p>
  <p>
    <strong>メールアドレス:</strong>
    <%= @user.email %>
  </p>
  <%= link_to '編集', edit_user_path(@user), class: "btn btn-primary" %>
</div>