config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'

  resources :users, only: %i[new create show edit update]
  resources :schedules, only: %i[index new create show edit update destroy] do
    resources :tasks, only: %i[create edit update destroy toggle_complete calculate_task_position], shallow: true do
      member do
        patch :toggle_complete
      end
    end
  end

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  post '/guest_login', to: 'sessions#guest_login'
end

app/views/shared/_before_login_header.html.erb
<header class="d-flex justify-content-between align-items-center mb-5">
  <h1 class="logo">
    <%= link_to 'PizzaSchedule', root_path, class: "text-decoration-none text-white" %>
  </h1>
  <div class="d-flex gap-3">
    <%= link_to '新規登録', new_user_path, class: "btn btn-primary btn-lg" %>
    <%= link_to 'ログイン', login_path, class: "btn btn-secondary btn-lg" %>
    <%= button_to 'ゲストログイン', guest_login_path, method: :post, class: "btn btn-outline-light btn-lg" %>
  </div>
</header>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>">
    <%= message %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer id='footer' class='footer-bottom'>
  <div class='container'>
    <div class='row'>
      <div class='col-sm-6 col-12'>
        <div class='copyright'>
          <p>Copyright © 2024. NAN</p>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header class="d-flex justify-content-between align-items-center mb-5">
  <h1 class="logo">
    <%= link_to 'PizzaSchedule', root_path, class: "text-decoration-none text-white" %>
  </h1>
  <div class="d-flex gap-3 align-items-center">
    <%= link_to 'スケジュール一覧', schedules_path, class: "btn btn-primary btn-lg" %>
    <%= link_to 'スケジュール作成', new_schedule_path, class: "btn btn-primary btn-lg" %>
    <%= link_to 'プロフィール', user_path(current_user), class: "btn btn-info btn-lg" %>
    <%= link_to 'ログアウト', logout_path, class: 'btn btn-secondary btn-lg', data: { turbo_method: :delete } %>
  </div>
</header>